---
settings:
  name: Cloud Volumes ONTAP 9.10.1 release notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-relnotes"
    version-number: 9.10.1
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-9100-relnotes"
    version-number: 9.10.0
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-991-relnotes"
    version-number: 9.9.1
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-990-relnotes"
    version-number: 9.9.0
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-98-relnotes"
    version-number: '9.8'
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-97-relnotes"
    version-number: '9.7'
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-96-relnotes"
    version-number: '9.6'
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-95-relnotes"
    version-number: '9.5'
  - name: Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-94-relnotes"
    version-number: '9.4'
  - name: ONTAP クラウド
    url: "/cloud-volumes-ontap-93-relnotes"
    version-number: '9.3'
  langs: ja-jp,us-en,zh-cn,ko-kr
sidebar:
  entries:
  - title: Cloud Manager のすべてのドキュメント
    url: https://docs.netapp.com/us-en/cloud-manager-family
  - title: リリースノートのホーム
    url: "/index.html"
  - title: 新機能
    url: "/reference-new.html"
  - title: ライセンスの概要
    url: "/concept-licensing.html"
  - title: サポートされている構成
    entries:
    - title: AWS
      url: "/reference-configs-aws.html"
    - title: Azure
      url: "/reference-configs-azure.html"
    - title: Google Cloud
      url: "/reference-configs-gcp.html"
  - title: ストレージの制限
    entries:
    - title: AWS
      url: "/reference-limits-aws.html"
    - title: Azure
      url: "/reference-limits-azure.html"
    - title: Google Cloud
      url: "/reference-limits-gcp.html"
  - title: 既知の問題
    url: "/reference-issues.html"
  - title: 既知の制限
    entries:
    - title: 一般的な制限事項
      url: "/reference-limitations.html"
    - title: AWS の制限事項
      url: "/reference-limitations-aws.html"
    - title: Azure の制限事項
      url: "/reference-limitations-azure.html"
    - title: Google Cloud の制限事項
      url: "/reference-limitations-gcp.html"
  - title: クラウドプロバイダの統合
    url: "/reference-provider-integrations.html"
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: 新機能
      url: reference-new.html
    - title: ライセンスの概要
      url: concept-licensing.html
  - title: Amazon Web Services の
    links:
    - title: サポートされている構成
      url: reference-configs-aws.html
    - title: ストレージの制限
      url: reference-limits-aws.html
    - title: 制限
      url: reference-limitations-aws.html
  - title: Google Cloud
    links:
    - title: サポートされている構成
      url: reference-configs-gcp.html
    - title: ストレージの制限
      url: reference-limits-gcp.html
    - title: 制限
      url: reference-limitations-gcp.html
  - title: Microsoft Azure
    links:
    - title: サポートされている構成
      url: reference-configs-azure.html
    - title: ストレージの制限
      url: reference-limits-azure.html
    - title: 制限
      url: reference-limitations-azure.html
  - title: ブログコミュニティ
    links:
    - title: ネットアップコミュニティ
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Cloud Central のブログです
      url: https://cloud.netapp.com/blog
    - title: クラウドに関する Web セミナー
      url: https://cloud.netapp.com/events
product-family: {}
