---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.12.1には、新しい機能強化が含まれています。 
---
= Cloud Volumes ONTAP 9.12.1の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.12.1には、新しい拡張機能が含まれています

その他の機能や拡張機能も、最新バージョンのBlueXP（旧Cloud Manager）で導入されました。を参照してください https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["BlueXPリリースノート"^] を参照してください。



== 9.12.1 GA（2023年2月9日）

Cloud Volumes ONTAP 9.12.1のGeneral Availability（GA）リリースが、AWS、Azure、Google Cloudで利用できるようになりました。GA リリースにはバグの修正が含まれています。



== 9.12.1 RC1（2022年12月8日）

Cloud Volumes ONTAP 9.12.1 Release Candidate 1は、AWS、Azure、Google Cloudで提供されるようになりました。このリリースには、次の新機能と機能拡張が含まれています。



=== GCPのONTAP S3ライセンス

ONTAP Cloud Platformでバージョン9.12.1以降を実行する新規および既存のCloud Volumes ONTAP システムに、S3ライセンスが含まれるようになりました。

https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["ONTAP で S3 オブジェクトストレージサービスを設定および管理する方法について説明します"^]



=== Cloud Volumes ONTAP でのNVMe-oF TCPのサポート

Cloud Volumes ONTAP バージョン9.12.1以降を使用している場合、クラウドプロバイダではnvme-tcpがサポートされます。BlueXPには、NVMe-oF TCPの管理機能はありません。

ONTAP を使用したNVMeの設定の詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-nvme-task.html["NVMe用のStorage VMを設定する"^]。



=== Azure HAは、管理対象ディスクを共有する単一のアベイラビリティゾーンで構成されます

共有管理対象ディスク上で実行されるMicrosoft Azureローカル冗長ストレージ（LRS）を使用して、Cloud Volumes ONTAP HA構成を導入できるようになりました。ローカルで冗長化されたストレージにより、同じリージョン内の1つのデータセンター内で3回、データがレプリケートされます。

HA構成のアーキテクチャとコンポーネントの詳細については、を参照してください link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html["Azure のハイアベイラビリティペア"^]。

Azureで単一のアベイラビリティゾーンに新しいHAペアを導入する場合は、ストレージにページBLOBではなくLRS共有管理ディスクを使用するようになります。作業環境ウィザードに変更はありません。この新しい構成を使用するには、単一のアベイラビリティゾーンを選択するだけです。詳細については、を参照してください link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-azure.html["AzureでのCloud Volumes ONTAP HAペアの起動"^]。



=== Azure HAは、共有管理対象ディスクを使用する複数のアベイラビリティゾーンで構成されます

リージョン内の複数のアベイラビリティゾーンを使用して、Cloud Volumes ONTAP HA構成を導入できるようになりました。この新しい構成は、Azureゾーン冗長ストレージ（ZRS）共有管理対象ディスクを使用して、データセンターの障害から保護し、アプリケーションの可用性を維持します。この機能は現在、米国西部2、西ヨーロッパ、北ヨーロッパ、フランス中部の地域でのみ利用できます。

HA構成のアーキテクチャとコンポーネントの詳細については、を参照してください link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html["Azure のハイアベイラビリティペア"^]。

この新しい設定を使用するには、を参照してください link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-azure.html["AzureでのCloud Volumes ONTAP HAペアの起動"^]。

管理対象ディスクのゾーン冗長ストレージの詳細については、を参照してください link:https://learn.microsoft.com/en-us/azure/virtual-machines/disks-redundancy#zone-redundant-storage-for-managed-disks["Microsoft Azureのドキュメント"]



== アップグレードに関する注意事項

このリリースへのアップグレードの詳細については、以下のメモをお読みください。



=== アップグレード方法

Cloud Volumes ONTAP のアップグレードは、BlueXPから完了している必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響を与える可能性

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXPから通知があった場合のアップグレード方法について説明します"^]。



=== サポートされているアップグレードパス

9.12.0および9.11.1リリースからCloud Volumes ONTAP 9.12.1にアップグレードできます。BlueXPでは、対象となるCloud Volumes ONTAP システムをこのリリースにアップグレードするように求められます。



=== 必要なコネクタのバージョン

新しいCloud Volumes ONTAP 9.12.1システムを導入し、既存のシステムを9.12.1にアップグレードするには、BlueXPコネクタがバージョン3.9.24以降を実行している必要があります。


TIP: コネクタの自動アップグレードはデフォルトで有効になっているため、最新バージョンを実行する必要があります。



=== ダウンタイム

* シングルノードシステムのアップグレードでは、 I/O が中断されるまで最大 25 分間システムがオフラインになります。
* HA ペアのアップグレードは無停止で、 I/O が中断されません。無停止アップグレードでは、各ノードが連携してアップグレードされ、クライアントへの I/O の提供が継続されます。




=== C4、M4、およびR4のインスタンスはサポートされなくなりました

AWSでは、C4、M4、およびR4 EC2インスタンスタイプはCloud Volumes ONTAP でサポートされなくなりました。C4、M4、またはR4インスタンスタイプで実行されている既存のシステムがある場合は、C5、m5、またはr5インスタンスファミリーでインスタンスタイプに変更する必要があります。

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["Cloud Volumes ONTAP のEC2インスタンスタイプを変更する方法について説明します"^]。

を参照してください link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["ネットアップサポート"^] これらのインスタンスタイプの可用性とサポート終了の詳細については、を参照してください。
