---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.11.0には、新しい拡張機能が追加されています。 
---
= Cloud Volumes ONTAP 9.11.0の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.11.0には、新しい拡張機能が追加されています。

その他の機能と機能拡張は、 Cloud Manager の最新バージョンで導入されました。を参照してください https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Cloud Manager リリースノート"^] を参照してください。



== 9.11.0 P1（2022年5月2日）

Cloud Volumes ONTAP 9.11.0 P1リリースがAWS、Azure、Google Cloudで利用できるようになりました。このリリースには、次の機能拡張が含まれています



=== AWSでのONTAP S3のサポート

AWSのCloud Volumes ONTAP からS3オブジェクトストレージを提供できるようになりました（Microsoft Azureはすでにサポートされています）。Cloud Volumes ONTAP は、NFSやSMBなどの従来型のファイルベースプロトコルに加え、スケールアウトストレージ用のオプションとしてS3をサポートしています。

次の点に注意してください。

* Cloud Volumes ONTAP S3 と ONTAP の主なユースケースは、汎用のオブジェクトストアです。
* 現時点では、Google CloudのCloud Volumes ONTAP ではS3プロトコルはサポートされていません。
* Cloud Manager には、 ONTAP S3 機能に対する管理機能はありません。


https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["ONTAP で S3 オブジェクトストレージサービスを設定および管理する方法について説明します"^]。



== アップグレードに関する注意事項

このリリースへのアップグレードの詳細については、以下のメモをお読みください。



=== アップグレード方法

Cloud Volumes ONTAP のアップグレードが Cloud Manager から完了している必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響を与える可能性

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["Cloud Manager から通知された場合のアップグレード方法について説明します"^]。



=== サポートされているアップグレードパス

9.10.1リリースからCloud Volumes ONTAP 9.11.0にアップグレードできます。対象となるCloud Volumes ONTAP システムをこのリリースにアップグレードするよう求めるプロンプトがCloud Managerに表示されます。



=== 必要なコネクタのバージョン

既存のシステムを9.11.0にアップグレードするには、Cloud Manager Connectorでバージョン3.9.18以降が実行されている必要があります。


TIP: コネクタの自動アップグレードはデフォルトで有効になっているため、最新バージョンを実行する必要があります。



=== ダウンタイム

* シングルノードシステムのアップグレードでは、 I/O が中断されるまで最大 25 分間システムがオフラインになります。
* HA ペアのアップグレードは無停止で、 I/O が中断されません。無停止アップグレードでは、各ノードが連携してアップグレードされ、クライアントへの I/O の提供が継続されます。




=== C4 、 M4 、および R4 インスタンスタイプ

9.8 リリース以降では、新しい Cloud Volumes ONTAP システムで C4 、 M4 、および R4 インスタンスタイプはサポートされません。C4 、 M4 、または R4 インスタンスタイプで実行されている既存の Cloud Volumes ONTAP システムがある場合も、このリリースにアップグレードできます。

C5 、 m5 、または r5 インスタンスファミリーのインスタンスタイプに変更することをお勧めします。
