---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP には、信頼性の高い運用を実現するために、 Google Cloud にストレージ構成の制限があります。最大のパフォーマンスを得るためには、システムを最大値で構成しないでください。 
---
= Google CloudでのCloud Volumes ONTAPのストレージ制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP には、安定した運用を実現するために、ストレージ構成の制限があります最大のパフォーマンスを得るためには、システムを最大値で構成しないでください。



== ライセンス別の最大システム容量

Cloud Volumes ONTAP システムの最大システム容量はライセンスで決まります。最大システム容量には、ディスクベースのストレージに加えて、データの階層化に使用されるオブジェクトストレージが含まれます。

NetApp はシステム容量制限の超過をサポートしていません。ライセンス容量の制限に達した場合、 NetAppコンソールにアクションが必要なメッセージが表示され、ディスクを追加できなくなります。

一部の構成では、ディスク制限により、ディスクのみを使用して容量制限に達することができません。を使用して容量の制限に達することができます https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["使用頻度の低いデータをオブジェクトストレージに階層化します"^]。詳細については、以下のディスク制限を参照してください。

.容量ベースのライセンスの容量制限
容量ベースのライセンスにより、各Cloud Volumes ONTAPシステムはオブジェクト ストレージへの階層化をサポートします。階層化された合計容量は、クラウド プロバイダーのバケット制限まで拡張できます。ライセンスには容量制限はありませんが、 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["『FabricPoolのベストプラクティス』"^]階層化を構成および管理する際に最適なパフォーマンス、信頼性、コスト効率を確保します。参照 https://cloud.google.com/storage/docs/buckets["Google Cloud ドキュメント"^]詳細についてはこちらをご覧ください。

他のライセンスタイプの容量制限::


[cols="25,75"]
|===
| 使用許諾 | 最大システム容量（ディスク + オブジェクトストレージ） 


| フリーミアム | 500 GB 


| PAYGO Explore | 2TB （ Explore ではデータ階層化はサポートされません） 


| PAYGO Standard の略 | 10 TB 


| PAYGO Premium | 368 TB 


| ノードベースのライセンス | 2PiB（複数のライセンスが必要） 
|===
.HA ペアの場合、ライセンスで許可されるノードあたりの容量制限はか、それとも HA ペア全体の容量制限ですか。
容量制限は HA ペア全体の容量制限です。ノード単位ではありません。たとえば、 Premium ライセンスを使用する場合、両方のノード間で最大 368 TB の容量を確保できます。

.HA ペアの場合、ミラーリングされたデータはライセンスで許可されている容量の上限にカウントされますか。
いいえ、違います。HA ペアのデータはノード間で同期的にミラーリングされるため、Google Cloud で障害が発生した場合でもデータを利用できます。たとえば、ノード A で 8 TB のディスクを購入した場合、コンソールはミラー化されたデータに使用されるノード B にも 8 TB のディスクを割り当てます。16 TB の容量が設定されていますが、ライセンス制限にカウントされるのは 8 TB のみです。



== アグリゲートの制限

Cloud Volumes ONTAP は、 Google Cloud Platform のディスクを _Aggregate_. にグループ化します。アグリゲートは、ボリュームにストレージを提供します。

[cols="2*"]
|===
| パラメータ | 制限（ Limit ） 


| 最大データアグリゲート数 ^1 ^  a| 
* シングルノードの場合は 99
* HA ペア全体で 64




| 最大アグリゲートサイズ | 256 TB の物理容量 ^2^ 


| アグリゲートあたりのディスク数 | 1-6^3^ 


| アグリゲートあたりの RAID グループの最大数 | 1. 
|===
注：

. データアグリゲートの最大数にルートアグリゲートは含まれません。
. アグリゲートを構成するディスクによって、アグリゲートの容量制限が決まります。この制限には、データ階層化に使用されるオブジェクト ストレージは含まれません。
. アグリゲート内のディスクはすべて同じサイズである必要があります。




== ディスクと階層化の制限

次の表に、ディスクのみの場合の最大システム容量と、オブジェクトストレージへのディスクおよびコールドデータの階層化を示します。ディスク制限はユーザデータが格納されたディスクに固有です。ブートディスク、ルートディスク、NVRAMは制限に含まれません。

[cols="60,40"]
|===
| パラメータ | 制限（ Limit ） 


| 最大データディスク数  a| 
* シングルノードシステムの場合は 124
* HA ペアの場合はノードあたり 123




| 最大ディスクサイズ | 64 TB 


| ディスクのみでの最大システム容量 | 256 TB^1 


| ディスクおよびコールドデータ階層化を使用した最大システム容量 Google Cloud Storage バケット | ライセンスによって異なります。上記の最大システム容量制限を参照してください。 
|===
^1 この制限は、 Google Cloud Platform の仮想マシンの制限により定義されています。



== Storage VM の制限

一部の構成では、 Cloud Volumes ONTAP 用に Storage VM （ SVM ）を追加で作成することができます。

これらはテストされた制限です。追加のストレージ VM の構成はサポートされていません。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["Storage VM を追加で作成する方法について説明します"^]。

[cols="2*"]
|===
| ライセンスタイプ | Storage VM の最大数 


| * Freemium *  a| 
合計24個のStorage VM：^1



| *容量ベースのPAYGOまたはBYOL *^2^  a| 
合計24個のStorage VM：^1



| *ノードベースのBYOL *^3^  a| 
合計24個のStorage VM：^1



| * ノードベースの PAYGO *  a| 
* データ提供用の Storage VM × 1
* ディザスタリカバリ用の Storage VM × 1


|===
. これらの 24 個の Storage VM からデータを提供することも、ディザスタリカバリ（ DR ）用に設定することもできます。
. 容量ベースのライセンスの場合、追加の Storage VM には追加のライセンスコストは発生しませんが、 Storage VM 1 台あたり最低容量は 4TiB 課金されます。たとえば、 2 台の Storage VM を作成し、それぞれに 2TiB のプロビジョニング済み容量がある場合、合計で 8TiB の容量が請求されます。
. ノードベースの BYOL の場合、 Cloud Volumes ONTAPにデフォルトで付属する最初のストレージ VM を超える追加のデータ提供ストレージ VM ごとにアドオン ライセンスが必要です。ストレージ VM アドオン ライセンスを取得するには、アカウント チームにお問い合わせください。
+
ディザスタリカバリ（ DR ）用に設定する Storage VM には追加ライセンスは必要ありませんが（無償）、 Storage VM の数は制限に含まれます。たとえば、ディザスタリカバリ用に設定されたデータ提供用の Storage VM が 12 台ある場合、上限に達し、それ以上 Storage VM を作成できません。





== 論理ストレージの制限

[cols="22,22,56"]
|===
| 論理ストレージ | パラメータ | 制限（ Limit ） 


.2+| * ファイル * | 最大サイズ^2^ | 128 TB 


| ボリュームあたりの最大数 | ボリュームサイズは最大 20 億個です 


| * FlexClone ボリューム * | クローン階層の深さ^12^ | 499 


.3+| * FlexVol ボリューム * | ノードあたりの最大数 | 500 


| 最小サイズ | 20 MB 


| 最大サイズ^3^ | 300TiB 


| * qtree * | FlexVol あたりの最大数 | 4,995 


| * Snapshot コピー * | FlexVol あたりの最大数 | 1,023 
|===
. クローン階層の深さは、 1 つの FlexVol から作成できる、ネストされた FlexClone ボリュームの最大階層です。
. ONTAP 9.12.1P2以降では、上限は128TBです。ONTAP 9.11.1以前のバージョンでは、最大16TBです。
. 次のツールと最小バージョンを使用して、最大サイズ300TiBまでのFlexVolボリュームを作成できます。
+
** Cloud Volumes ONTAP 9.12.1 P2 および 9.13.0 P2 以降の System Manager およびONTAP CLI
** Cloud Volumes ONTAP 9.13.1から






== iSCSI ストレージの制限

[cols="3*"]
|===
| iSCSI ストレージ | パラメータ | 制限（ Limit ） 


.4+| * LUN* | ノードあたりの最大数 | 1,024 


| LUN マップの最大数 | 1,024 


| 最大サイズ | 16 TB 


| ボリュームあたりの最大数 | 512 


| * igroup 数 * | ノードあたりの最大数 | 256 


.2+| * イニシエータ * | ノードあたりの最大数 | 512 


| igroup あたりの最大数 | 128 


| * iSCSI セッション * | ノードあたりの最大数 | 1,024 


.2+| * LIF * | ポートあたりの最大数 | 1. 


| ポートセットあたりの最大数 | 32 


| * ポートセット * | ノードあたりの最大数 | 256 
|===


== Cloud Volumes ONTAP HA ペアでは、ストレージの迅速な使用はサポートされません ギブバック

ノードがリブートしたら、ストレージを戻す前に、パートナーがデータを同期する必要があります。データの再同期にかかる時間は、ノードが停止している間にクライアントが書き込んだデータの量、およびギブバックの実行中のデータの書き込み速度によって異なります。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-google-cloud.html["Google Cloudで実行されるCloud Volumes ONTAP HAペアのストレージの仕組みを説明します"^]。
