---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: 既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください 
---
= すべてのクラウドプロバイダにおけるCloud Volumes ONTAPの既知の制限事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください

すべてのクラウドプロバイダの Cloud Volumes ONTAP に、 AWS 、 Azure 、 Google Cloud の制限が適用されます。



== サポートされない ONTAP 機能です

Cloud Volumes ONTAP では、次の機能はサポートされていません。

* アグリゲートレベルのインライン重複排除
* アグリゲートレベルのバックグラウンド重複排除
* ディスクメンテナンスセンター
* ディスク完全消去
* FabricPool ミラーリング
* Fibre Channel （ FC ；ファイバチャネル）
* Flash Pool の機能です
* Infinite Volume
* インターフェイスグループ
* ノード内の LIF のフェイルオーバー
* MetroCluster
* 管理者による検証が複数必要です
+
Cloud Volumes ONTAP でマルチ管理者検証を有効にすると、構成がサポートされなくなります。

* RAID 4 、 RAID-DP 、 RAID-TEC （ RAID 0 のサポート）
* サービスプロセッサ
* SnapLock のコンプライアンスモードとエンタープライズモード（クラウドの WORM のみサポート）
* SnapMirror Synchronous
* VLAN
* SMB 継続的な可用性 (CA)
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["継続的可用性を備えたSMB共有"^]中断のない運用はサポートされていません。





== 最大同時レプリケーション処理数

Cloud Volumes ONTAP で同時に実行できる SnapMirror 転送または SnapVault 転送の最大数は、インスタンスのタイプやマシンのタイプに関係なく、ノードあたり 100 です。



== クラウドプロバイダの Snapshot をバックアップとリカバリの計画に使用しないでください

クラウドプロバイダのスナップショットは、 Cloud Volumes ONTAP データのバックアップとリカバリの計画には使用しないでください。Cloud Volumes ONTAP でホストされているデータのバックアップとリストアには、必ず ONTAP の Snapshot コピーや他社製のバックアップソリューションを使用してください。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["NetApp Backup and Recoveryを使用してONTAPデータをバックアップおよび復元する方法を学びます"^] 。


NOTE: データの整合性は、 WAFL ファイルシステムの ONTAP 整合ポイントによって決まります。WAFL ファイルシステムを休止して crash-consistent バックアップを実行できるのは、 ONTAP のみです。



== Cloud Volumes ONTAPはリザーブドVMインスタンスとオンデマンドVMインスタンスのみをサポート

Cloud Volumes ONTAP は、クラウドプロバイダから予約済みまたはオンデマンドの VM インスタンスのいずれかで実行できます。それ以外のタイプの VM インスタンスはサポートされません。



== 自動アプリケーションリソース管理ソリューションは使用しないでください

アプリケーションリソースの自動管理ソリューションでは、 Cloud Volumes ONTAP システムを管理しないでください。サポートされていない構成に変更される可能性があります。たとえば、このソリューションでは、 Cloud Volumes ONTAP をサポート対象外の VM インスタンスタイプに変更する場合があります。



== ソフトウェアアップデートはNetAppコンソールで完了する必要があります

Cloud Volumes ONTAPのアップグレードは、 NetAppコンソールから完了する必要があります。System Manager または CLI を使用してCloud Volumes ONTAP をアップグレードしないでください。システムの安定性に影響を与える可能性があります。



== から Cloud Volumes ONTAP 環境を変更することはできません クラウドプロバイダのコンソール

クラウド プロバイダーのコンソールからCloud Volumes ONTAP構成を変更すると、サポートされていない構成になります。コンソールが作成および管理するCloud Volumes ONTAPリソースに変更を加えると、システムの安定性と、コンソールがシステムを管理する能力に影響する可能性があります。


NOTE: 初期導入後は、Cloud Volumes ONTAPリソースに使用するAzureサブスクリプション名の変更がサポートされます。



== ディスクとアグリゲートはコンソールから管理する必要がある

すべてのディスクとアグリゲートは、コンソールから直接作成および削除する必要があります。これらのアクションを別の管理ツールから実行しないでください。そうすると、システムの安定性に影響が及び、将来的にディスクを追加する能力が妨げられ、クラウド プロバイダーの料金が重複して発生する可能性があります。



== SnapManager のライセンスに関する制限

SnapManager のサーバ単位のライセンスは、 Cloud Volumes ONTAP でサポートされます。ストレージシステム（ SnapManager スイート）単位のライセンスはサポートされません。



== サードパーティエージェントおよび拡張機能の制限事項

サードパーティのエージェントおよびVM拡張機能は、Cloud Volumes ONTAP仮想マシンインスタンスではサポートされていません。
