---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: 信頼性の高い運用を実現するために、 Cloud Volumes ONTAP には AWS にストレージ構成の制限があります。最大のパフォーマンスを得るためには、システムを最大値で構成しないでください。 
---
= AWS の Cloud Volumes ONTAP でのストレージの制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP には、安定した運用を実現するために、ストレージ構成の制限があります最大のパフォーマンスを得るためには、システムを最大値で構成しないでください。



== ライセンス別の最大システム容量

最大システム容量には、ディスクベースのストレージと、データ階層化に使用されるオブジェクト ストレージが含まれます。

NetApp はシステム容量制限の超過をサポートしていません。ライセンス容量の制限に達した場合、 NetAppコンソールにアクションが必要なメッセージが表示され、ディスクを追加できなくなります。

一部の構成では、ディスク制限により、ディスクのみを使用して容量制限に達することができません。その場合、で容量の制限に達することができます https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["使用頻度の低いデータをオブジェクトストレージに階層化します"^]。詳細については、以下の容量とディスクの制限を参照してください。

.容量ベースのライセンスの容量制限
容量ベースのライセンスにより、各Cloud Volumes ONTAPシステムはオブジェクト ストレージへの階層化をサポートします。階層化された合計容量は、クラウド プロバイダーのバケット制限まで拡張できます。ライセンスには容量制限はありませんが、 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["『FabricPoolのベストプラクティス』"^]階層化を構成および管理する際に最適なパフォーマンス、信頼性、コスト効率を確保します。参照 https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["AWSのドキュメント"^]詳細についてはこちらをご覧ください。

他のライセンスタイプの容量制限::


[cols="25,75"]
|===
| 使用許諾 | 最大システム容量（ディスク + オブジェクトストレージ） 


| フリーミアム | 500 GiB 


| PAYGO Explore | 2TiB （ Explore ではデータ階層化はサポートされません） 


| PAYGO Standard の略 | 10TiB 


| PAYGO Premium | 368TiB 


| ノードベースのライセンス | 2PiB（複数のライセンスが必要） 
|===
.HA の場合、ライセンスの容量制限はノード単位か、 HA ペア全体に適用されるか
容量制限は HA ペア全体に適用されます。ノードごとではありません。たとえば、プレミアム ライセンスでは、両方のノードで最大 368 TiB が許可されます。

.AWS の HA システムでは、ミラーリングされたデータは容量制限にカウントされますか。
いいえ、違います。AWS HA ペアのデータはノード間で同期的にミラーリングされるため、障害発生時にもデータを利用できます。たとえば、ノード A で 8 TiB のディスクを購入した場合、コンソールはミラーリングされたデータに使用されるノード B にも 8 TiB のディスクを割り当てます。16 TiB の容量がプロビジョニングされましたが、ライセンス制限にカウントされるのは 8 TiB のみです。



== アグリゲートの制限

Cloud Volumes ONTAP はEBSボリュームをディスクとして使用し、アグリゲートにグループ化します。アグリゲートは、ボリュームにストレージを提供します。

[cols="2*"]
|===
| パラメータ | 制限（ Limit ） 


| アグリゲートの最大数 | 1 つのノード：ディスクリミットの HA ペアと同じです：ノード ^1 の 18 


| 最大アグリゲートサイズ^2^  a| 
* 96TiB の物理容量
* Elastic Volumesの場合、128TiBの物理容量^3^




| アグリゲートあたりのディスク数^4^  a| 
* 1 ～ 6
* 1 ~ 8（Elastic Volumesを使用）^3^




| アグリゲートあたりの RAID グループの最大数 | 1. 
|===
注：

. データ ディスクの制限を超えてしまうため、HA ペアの両方のノードに 18 個のアグリゲートを作成することはできません。
. 最大集約サイズはディスクによって異なり、データ階層化に使用するオブジェクト ストレージは含まれません。
. Amazon EBS Elastic Volumes 機能をサポートする構成の場合、アグリゲートには最大 8 個のディスクを含めることができ、最大 128 TiB の容量が提供されます。デフォルトでは、 Cloud Volumes ONTAP 9.11.0 以降のシステムでは、gp3 または io1 ディスクを使用する場合、Amazon EBS Elastic Volumes が有効になっています。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Elastic Volumesのサポートに関する詳細情報"^]
. アグリゲート内のディスクはすべて同じサイズである必要があります。




== ディスクおよび階層化の制限は EC2 インスタンスごとに適用されます

容量制限は、使用するEC2インスタンスタイプファミリーと、シングルノードシステムとHAペアのどちらを使用しているかによって異なります。

次のメモは、下の表に表示される数値の詳細を示しています。

* ディスク制限はユーザデータが格納されたディスクに固有です。
+
この制限には、ブートディスクとルートディスクは含まれていません。

* ディスクのみを使用する場合、およびディスクとオブジェクトストレージへのコールドデータ階層化を使用する場合は、最大システム容量が表示されます。
* Cloud Volumes ONTAP は EBS ボリュームをディスクとして使用し、最大ディスクサイズは 16TiB です。




=== 容量ベースのライセンスのさまざまな展開モードの制限

容量ベースのライセンスパッケージを使用するCloud Volumes ONTAP システムには、次のディスク制限が適用されます。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP のライセンスオプションについて説明します"^]


NOTE: 単一ノードおよびHA構成の最大システム容量とデータ階層化容量の制限については、以下を参照してください。<<cap-license-aws>> 。



==== シングルノード

[cols="18,18,32,width=100%,options="]
|===


| インスタンス | ノードあたりの最大ディスク数 | ディスクのみの場合の最大システム容量 


| C5 、 m5 、および r5 インスタンス | 21 | 336 TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge（m6id.32xlarge）

| 19^1 ^ | 304 TiB 
|===
. このインスタンスタイプのローカル NVMe ディスクの数は他のインスタンスタイプよりも多く、サポートされるデータディスクの数が少なくなります。




==== HA ペア

[cols="18,18,32,width=100%,options="]
|===


| インスタンス | ノードあたりの最大ディスク数 | ディスクのみの場合の最大システム容量 


| C5 、 m5 、および r5 インスタンス | 18 | 288TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge（m6id.32xlarge）

| 16^1 ^ | 256TiB です 
|===
. このインスタンスタイプのローカル NVMe ディスクの数は他のインスタンスタイプよりも多く、サポートされるデータディスクの数が少なくなります。




=== ノードベースライセンスのさまざまな展開モードの制限

次のディスク制限は、ノード単位のライセンスをCloud Volumes ONTAP に付与することが可能な旧世代のライセンスモデルであるノードベースのライセンスを使用するCloud Volumes ONTAP システムに適用されます。既存のお客様は、ノードベースのライセンスを引き続き利用できます。

Cloud Volumes ONTAP BYOLシングルノードまたはHAペアシステム用に複数のノードベースライセンスを購入して、368TiBを超える容量を割り当てることができます（テストおよびサポートされるシステム容量の上限である2PiBまで）。ディスク制限によって、ディスクだけを使用することで容量制限に達することがないことに注意してください。を使用すると、ディスク制限を超えることができます https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["使用頻度の低いデータをオブジェクトストレージに階層化します"^]。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Cloud Volume にシステムライセンスを追加する方法について説明します ONTAP"^]。Cloud Volumes ONTAPでは、テストおよびサポートされる最大システム容量2PiBまでサポートされますが、2PiBの制限を超えると、サポートされないシステム構成になります。

AWS Secret CloudリージョンとTop Secret Cloudリージョンでは、Cloud Volumes ONTAP 9.12.1以降で複数のノードベースライセンスの購入がサポートされます。



==== PAYGO Premiumでは1つのノード

[cols="18,18,32,32"]
|===
| インスタンス | ノードあたりの最大ディスク数 | ディスクのみの場合の最大システム容量 | ディスクとデータ階層化による最大システム容量 


| C5 、 m5 、および r5 インスタンス | 21^1 ^ | 336 TiB | 368TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge（m6id.32xlarge）

| 19^2^ | 304 TiB | 368TiB 
|===
. Cloud Volumes ONTAP の _NET_Deployments には、 21 本のデータディスクが制限されています。バージョン 9.7 以前で作成されたシステムをアップグレードしても、 22 本のディスクが引き続きサポートされます。9.8 リリース以降のコアディスクが追加されているため、これらのインスタンスタイプを使用する新しいシステムでは、サポートされるデータディスクは 1 本少なくなります。
. このインスタンスタイプのローカル NVMe ディスクの数は他のインスタンスタイプよりも多く、サポートされるデータディスクの数が少なくなります。




==== BYOLによるシングルノード

[cols="18,18,16,16,16,16"]
|===
| インスタンス | ノードあたりの最大ディスク数 2+| 最大システム容量（ 1 ライセンス 2+| 複数のライセンスを持つ最大システム容量 


2+|  | * ディスクのみ * | * ディスク + データ階層化 * | * ディスクのみ * | * ディスク + データ階層化 * 


| C5 、 m5 、および r5 インスタンス | 21^1 ^ | 336 TiB | 368TiB | 336 TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge（m6id.32xlarge）

| 19^2^ | 304 TiB | 368TiB | 304 TiB | 2 PiB 
|===
. Cloud Volumes ONTAP の _NET_Deployments には、 21 本のデータディスクが制限されています。バージョン 9.7 以前で作成されたシステムをアップグレードしても、 22 本のディスクが引き続きサポートされます。9.8 リリース以降のコアディスクが追加されているため、これらのインスタンスタイプを使用する新しいシステムでは、サポートされるデータディスクは 1 本少なくなります。
. このインスタンスタイプのローカル NVMe ディスクの数は他のインスタンスタイプよりも多く、サポートされるデータディスクの数が少なくなります。




==== PAYGO PremiumでHAペアを構成

[cols="18,18,32,32"]
|===
| インスタンス | ノードあたりの最大ディスク数 | ディスクのみの場合の最大システム容量 | ディスクとデータ階層化による最大システム容量 


| C5 、 m5 、および r5 インスタンス | 18^1 ^ 1^ | 288TiB | 368TiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge（m6id.32xlarge）

| 16^2^ | 256TiB です | 368TiB 
|===
. 18 本のデータディスクは、 Cloud Volumes ONTAP の _new_Deployments の制限です。バージョン 9.7 以前で作成されたシステムをアップグレードしても、システムでは 19 本のディスクが引き続きサポートされます。9.8 リリース以降のコアディスクが追加されているため、これらのインスタンスタイプを使用する新しいシステムでは、サポートされるデータディスクは 1 本少なくなります。
. このインスタンスタイプのローカル NVMe ディスクの数は他のインスタンスタイプよりも多く、サポートされるデータディスクの数が少なくなります。




==== BYOLによるHAペア

[cols="18,18,16,16,16,16"]
|===
| インスタンス | ノードあたりの最大ディスク数 2+| 最大システム容量（ 1 ライセンス 2+| 複数のライセンスを持つ最大システム容量 


2+|  | * ディスクのみ * | * ディスク + データ階層化 * | * ディスクのみ * | * ディスク + データ階層化 * 


| C5 、 m5 、および r5 インスタンス | 18^1 ^ 1^ | 288TiB | 368TiB | 288TiB | 2 PiB 


 a| 
* m5dn.24xlarge
* m6id.32xlarge（m6id.32xlarge）

| 16^2^ | 256TiB です | 368TiB | 256TiB です | 2 PiB 
|===
. 18 本のデータディスクは、 Cloud Volumes ONTAP の _new_Deployments の制限です。バージョン 9.7 以前で作成されたシステムをアップグレードしても、システムでは 19 本のディスクが引き続きサポートされます。9.8 リリース以降のコアディスクが追加されているため、これらのインスタンスタイプを使用する新しいシステムでは、サポートされるデータディスクは 1 本少なくなります。
. このインスタンスタイプのローカル NVMe ディスクの数は他のインスタンスタイプよりも多く、サポートされるデータディスクの数が少なくなります。




== Storage VM の制限

一部の構成では、 Cloud Volumes ONTAP 用に Storage VM （ SVM ）を追加で作成することができます。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-aws.html["Storage VM を追加で作成する方法について説明します"^]。

[cols="40,60"]
|===
| ライセンスタイプ | Storage VM の最大数 


| * Freemium *  a| 
合計 24 個の Storage VM の合計 ^ 1 、 2 、 ^



| * 容量ベースの PAYGO または BYOL * ^3^  a| 
合計 24 個の Storage VM の合計 ^ 1 、 2 、 ^



| * ノードベースの PAYGO *  a| 
* データ提供用の Storage VM × 1
* ディザスタリカバリ用の Storage VM × 1




| * ノードベースの BYOL * ^4^  a| 
* 合計 24 個の Storage VM の合計 ^ 1 、 2 、 ^


|===
. 使用する EC2 インスタンスタイプによっては、上限値がそれよりも低くなる可能性があります。インスタンスあたりの制限は、以下のセクションに記載されています。
. これらの 24 個の Storage VM からデータを提供することも、ディザスタリカバリ（ DR ）用に設定することもできます。
. 容量ベースのライセンスの場合、追加の Storage VM には追加のライセンスコストは発生しませんが、 Storage VM 1 台あたり最低容量は 4TiB 課金されます。たとえば、 2 台の Storage VM を作成し、それぞれに 2TiB のプロビジョニング済み容量がある場合、合計で 8TiB の容量が請求されます。
. ノードベースの BYOL の場合、デフォルトでは、 Cloud Volumes ONTAP に付属する最初の Storage VM 以降の追加の DATA Serving_storage VM ごとにアドオンライセンスが必要です。アカウントチームに問い合わせて Storage VM アドオンライセンスを取得してください。
+
ディザスタリカバリ（ DR ）用に設定する Storage VM には追加ライセンスは必要ありませんが（無償）、 Storage VM の数は制限に含まれます。たとえば、ディザスタリカバリ用に設定されたデータ提供用の Storage VM が 12 台ある場合、上限に達し、それ以上 Storage VM を作成できません。





=== EC2 インスタンスタイプごとに Storage VM の制限が設定されています

Storage VM を追加で作成する場合は、ポート e0a にプライベート IP アドレスを割り当てる必要があります。次の表に、インターフェイスごとのプライベート IP の最大数と、 Cloud Volumes ONTAP の導入後にポート e0a で使用可能な IP アドレスの数を示します。使用可能な IP アドレスの数は、その構成での Storage VM の最大数に直接影響します。

次のインスタンスは、 C5 、 m5 、および r5 インスタンスファミリを対象としています。

[cols="6*"]
|===
| 設定 | インスタンスタイプ | インターフェイスあたりのプライベート IP の最大数 | 展開後の IPS の残り時間 ^1 | 管理 LIF がない Storage VM の最大数 ^2 、 3^ | 管理 LIF を使用している Storage VM の最大数 ^2 、 3^ 


.9+| * シングルノード * | * 。 x ラージ | 15 | 9. | 10. | 5. 


| *.2xlarge | 15 | 9. | 10. | 5. 


| *.< ：と入力します | 30 | 24 | 24 | 12. 


| * 。 8xlarge | 30 | 24 | 24 | 12. 


| * 。 9xlarge | 30 | 24 | 24 | 12. 


| * 。 12xlarge | 30 | 24 | 24 | 12. 


| *.16 x ラージ | 50 | 44 | 24 | 12. 


| *. 18 倍 | 50 | 44 | 24 | 12. 


| *. 24xlarge | 50 | 44 | 24 | 12. 


.9+| * 単一の AZ* で HA ペア | * 。 x ラージ | 15 | 10. | 11. | 5. 


| *.2xlarge | 15 | 10. | 11. | 5. 


| *.< ：と入力します | 30 | 25 | 24 | 12. 


| * 。 8xlarge | 30 | 25 | 24 | 12. 


| * 。 9xlarge | 30 | 25 | 24 | 12. 


| * 。 12xlarge | 30 | 25 | 24 | 12. 


| *.16 x ラージ | 50 | 45 | 24 | 12. 


| *. 18 倍 | 50 | 45 | 24 | 12. 


| *. 24xlarge | 50 | 44 | 24 | 12. 


.9+| * 複数の AZ にまたがる HA ペア * | * 。 x ラージ | 15 | 12. | 13 | 13 


| *.2xlarge | 15 | 12. | 13 | 13 


| *.< ：と入力します | 30 | 27 | 24 | 24 


| * 。 8xlarge | 30 | 27 | 24 | 24 


| * 。 9xlarge | 30 | 27 | 24 | 24 


| * 。 12xlarge | 30 | 27 | 24 | 24 


| *.16 x ラージ | 50 | 47 | 24 | 24 


| *. 18 倍 | 50 | 47 | 24 | 24 


| *. 24xlarge | 50 | 44 | 24 | 12. 
|===
. この数値は、 Cloud Volumes ONTAP の導入とセットアップ後にポート e0a で使用可能な残りのプライベート IP アドレスの数を示します。たとえば、 *.2xlarge システムでは、ネットワークインターフェイスごとに最大 15 の IP アドレスがサポートされます。単一の AZ に HA ペアを導入すると、 5 つのプライベート IP アドレスがポート e0a に割り当てられます。そのため、インスタンスタイプが *.2xlarge の HA ペアでは、追加の Storage VM 用にプライベート IP アドレスが 10 個残っています。
. これらの列にリストされる数には、コンソールがデフォルトで作成する初期ストレージ VM が含まれます。たとえば、この列に 24 と表示されている場合は、合計 24 台の追加ストレージ VM を 23 台作成できることを意味します。
. Storage VM の管理 LIF はオプションです。管理 LIF は、 SnapCenter などの管理ツールへの接続を提供します。
+
プライベート IP アドレスが必要なため、追加で作成できる Storage VM の数が制限されます。ただし、複数の AZ にまたがる HA ペアは例外です。この場合、管理 LIF の IP アドレスは _floating_ip アドレスであるため、 _private_IP 制限にはカウントされません。





== ファイルとボリュームの制限

[cols="22,22,56"]
|===
| 論理ストレージ | パラメータ | 制限（ Limit ） 


.2+| * ファイル * | 最大サイズ^2^ | 128 TB 


| ボリュームあたりの最大数 | ボリュームサイズは最大 20 億個です 


| * FlexClone ボリューム * | クローン階層の深さ ^1^ | 499 


.3+| * FlexVol ボリューム * | ノードあたりの最大数 | 500 


| 最小サイズ | 20 MB 


| 最大サイズ^3^ | 300TiB 


| * qtree * | FlexVol あたりの最大数 | 4,995 


| * Snapshot コピー * | FlexVol あたりの最大数 | 1,023 
|===
. クローン階層の深さは、 1 つの FlexVol から作成できる、ネストされた FlexClone ボリュームの最大階層です。
. ONTAP 9.12.1P2以降では、上限は128TBです。ONTAP 9.11.1以前のバージョンでは、最大16TBです。
. 次のツールと最小バージョンを使用して、最大サイズ300TiBまでのFlexVolボリュームを作成できます。
+
** System ManagerとONTAP CLI（Cloud Volumes ONTAP 9.12.1 P2および9.13.0 P2以降）
** Cloud Volumes ONTAP 9.13.1から






== iSCSI ストレージの制限

[cols="3*"]
|===
| iSCSI ストレージ | パラメータ | 制限（ Limit ） 


.4+| * LUN* | ノードあたりの最大数 | 1,024 


| LUN マップの最大数 | 1,024 


| 最大サイズ | 16TiB 


| ボリュームあたりの最大数 | 512 


| * igroup 数 * | ノードあたりの最大数 | 256 


.2+| * イニシエータ * | ノードあたりの最大数 | 512 


| igroup あたりの最大数 | 128 


| * iSCSI セッション * | ノードあたりの最大数 | 1,024 


.2+| * LIF * | ポートあたりの最大数 | 32 


| ポートセットあたりの最大数 | 32 


| * ポートセット * | ノードあたりの最大数 | 256 
|===