---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.15.0には、新しい機能拡張が含まれています。 
---
= Cloud Volumes ONTAP 9.15.0の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.15.0には、新しい機能拡張が含まれています。

その他の機能と拡張機能も、最新バージョンのBlueXPで導入されました。を参照してください https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXPリリースノート"^] を参照してください。



== 9.15.0 P1（2024年6月10日）

Cloud Volumes ONTAP 9.15.0 P1がAWS、Azure、Google Cloudで利用できるようになりました。P1バージョンは導入とアップグレードに使用できます。

このリリースには、新機能と機能拡張が含まれています。



=== Azureでの画像検証

Azure経由でエクスポートされたCloud Volumes ONTAPイメージファイルの署名を検証するための強化されたセキュリティ機能が利用できるようになりました。

詳細については、を参照してください link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-azure-image-verification.html["Azureイメージ検証の詳細"^]。



=== ハイアベイラビリティペアの新規導入では、AzureページBLOBがサポートされなくなりました。

Cloud Volumes ONTAP 9.15.0 P1以降では、ハイアベイラビリティペアの新規導入でAzureページBLOBがサポートされなくなりました。既存のハイアベイラビリティペア環境でAzureページBLOBを使用している場合は、Edsv4シリーズVMおよびEdsv5シリーズVMの新しいVMインスタンスタイプに移行できます。

link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#ha-pairs["Azureでサポートされる構成の詳細"^]。



== アップグレードに関する注意事項

このリリースへのアップグレードの詳細については、以下のメモをお読みください。



=== アップグレード方法

Cloud Volumes ONTAP のアップグレードは、BlueXPから完了している必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響を与える可能性

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXPから通知があった場合のアップグレード方法について説明します"^]。



=== サポートされているアップグレードパス

Cloud Volumes ONTAP 9.14.1リリースから9.15.0にアップグレードできます。BlueXPでは、対象となるCloud Volumes ONTAP システムをこのリリースにアップグレードするように求められます。



=== ダウンタイム

* シングルノードシステムのアップグレードでは、 I/O が中断されるまで最大 25 分間システムがオフラインになります。
* HA ペアのアップグレードは無停止で、 I/O が中断されません。無停止アップグレードでは、各ノードが連携してアップグレードされ、クライアントへの I/O の提供が継続されます。




=== C4、M4、およびR4のインスタンスはサポートされなくなりました

AWSでは、C4、M4、およびR4 EC2インスタンスタイプはCloud Volumes ONTAP でサポートされなくなりました。C4、M4、またはR4インスタンスタイプで実行されている既存のシステムがある場合は、C5、m5、またはr5インスタンスファミリーでインスタンスタイプに変更する必要があります。インスタンスタイプを変更するまで、このリリースにアップグレードすることはできません。

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Cloud Volumes ONTAP のEC2インスタンスタイプを変更する方法について説明します"^]。

を参照してください link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["ネットアップサポート"^] これらのインスタンスタイプの可用性とサポート終了の詳細については、を参照してください。
