---
sidebar: sidebar 
permalink: reference-configs-gcp.html 
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs 
summary: Google Cloud では、いくつかの Cloud Volumes ONTAP 構成がサポートされています。 
---
= Google CloudのCloud Volumes ONTAPでサポートされる構成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud では、いくつかの Cloud Volumes ONTAP 構成がサポートされています。



== ライセンスでサポートされている構成

Cloud Volumes ONTAP は Google Cloud では、単一ノード システムとして、またフォールト トレランスと無停止運用を実現する高可用性（HA）ノード ペアとして利用できます。

単一ノード システムを HA ペアにアップグレードすることはサポートされていません。単一ノード システムと HA ペアを切り替える場合は、新しいシステムを展開し、既存のシステムから新しいシステムにデータを複製する必要があります。

Cloud Volumes ONTAP は、クラウドプロバイダから予約済みまたはオンデマンドの VM インスタンスのいずれかで実行できます。他の種類の VM インスタンスを使用するソリューションはサポートされていません。

[role="tabbed-block"]
====
.容量ベースのライセンス
--
[cols="h,d,d,d"]
|===
|  | フリーミアム | 最適化されました ^4^ | 容量ベースのライセンス（EssentialsおよびProfessional） 


| 最大システム容量（ディスク + オブジェクトストレージ） | 500 GiB  a| 
容量ベースのライセンスにより、各Cloud Volumes ONTAPシステムはオブジェクト ストレージへの階層化をサポートします。階層化された合計容量は、クラウド プロバイダーのバケット制限まで拡張できます。ライセンスには容量制限はありませんが、 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["『FabricPoolのベストプラクティス』"^]階層化を構成および管理する際に最適なパフォーマンス、信頼性、コスト効率を確保します。



| サポートされているマシンタイプ ^1  a| 
* N1-STANDARD-8^1^
* N1-STANDARD-32^1^
* N2 - 標準 -4
* N2-standard-8
* N2-standard-16
* N2-standard-32
* N2-STANDARD-48
* N2-STANDARD-64

 a| 
* N2 - 標準 -4
* N2-standard-8

 a| 
* N1-STANDARD-8^1^
* N1-STANDARD-32^1^
* N2 - 標準 -4
* N2-standard-8
* N2-standard-16
* N2-standard-32
* N2-STANDARD-48
* N2-STANDARD-64




| サポートされているディスクタイプ ^2^ 3+| バランスの取れた永続ディスク^3^、パフォーマンス（SSD）永続ディスク^3^、および標準（HDD）永続ディスク。 
|===
注：

. ^1^ Google Cloud にCloud Volumes ONTAPの新しいインスタンスをデプロイするときに、n1 シリーズのマシンはNetAppコンソールで選択できなくなりました。n1 シリーズのマシンは、古い既存のシステムでのみ保持され、サポートされます。Cloud Volumes ONTAPの新しいデプロイメントは、Google Cloud 9.8 リリース以降でのみサポートされます。Cloud Volumes ONTAP 9.8 以降と互換性のある n2 シリーズ マシンに切り替えることをお勧めします。ただし、n1 シリーズのマシンは、API を通じて行われる新しい展開では利用できるようになります。
+
新しい Cloud Volumes ONTAP システムでは、 custom-4-16384 マシンタイプはサポートされなくなりました。このタイプのマシンで既存のシステムを実行している場合は、引き続き使用できますが、 n2 標準 -4 マシンタイプに切り替えることをお勧めします。

. ^2^ディスク制限により、ディスクのみを使用してもシステム容量の上限に達することができない場合があります。容量制限には、で到達できます https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["使用頻度の低いデータをオブジェクトストレージに階層化します"^]。
+
link:reference-limits-gcp.html["Google Cloud のディスク制限について詳しくは、こちらをご覧ください"]。

. ^3^Balanced Persistent DiskおよびPerformance（SSD）Persistent Diskを使用すると、書き込みパフォーマンスの向上が有効になります。
+
Cloud Volumes ONTAP 9.13.0以降では、次のHAペア導入インスタンスで_Flash Cache_、高速の書き込み速度、最大伝送ユニット（MTU）8、896バイトを使用できます。

+
** N2-standard-16
** N2-standard-32
** N2-STANDARD-48
** N2-STANDARD-64
+
対象となるインスタンスタイプを導入する際に、_Flash Cache__、および高速の書き込み速度を有効にすることができます。より高い最大伝送単位（8、896バイト）をイネーブルにするには、導入環境でVPC-1、VPC-2、またはVPC-3を選択する必要があります。MTUが大きいほど、ネットワークスループットが向上します。これらの配置のいずれかを起動する方法の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Google CloudでのHAペアの起動"]。

+

NOTE: _Flash Cache _、高書き込みモード、MTU 8、896は機能に依存し、設定されたインスタンス内で個別に無効にすることはできません。



. ^4^ 2025 年 8 月 11 日以降、 Cloud Volumes ONTAP Optimized ライセンスは非推奨となり、従量課金制 (PAYGO) サブスクリプションの Google Cloud マーケットプレイスで購入または更新できなくなります。詳細については、 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP の新機能"^] 。


--
.ノードベースのライセンス
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explore | PAYGO Standard の略 | PAYGO Premium | ノードベースの BYOL 


| 最大システム容量（ディスク + オブジェクトストレージ） | 2 TB ^2^ | 10TiB | 368TiB | 1 ライセンスあたり 368 TiB 


| サポートされているマシンタイプ ^3  a| 
* N2 - 標準 -4

 a| 
* N1-STANDARD-8^3^
* N2-standard-8

 a| 
* N1-STANDARD-32^3^
* N2-standard-16
* N2-standard-32
* N2-STANDARD-48
* N2-STANDARD-64

 a| 
* N1-STANDARD-8^3^
* N1-STANDARD-32^3^
* N2 - 標準 -4
* N2-standard-8
* N2-standard-16
* N2-standard-32
* N2-STANDARD-48
* N2-STANDARD-64




| サポートされているディスクタイプ 4+| バランスの取れた永続ディスク^4^、パフォーマンス（SSD）永続ディスク^4^、および標準（HDD）永続ディスク。 
|===
注：

. ^1^ディスク制限により、ディスクのみを使用してもシステム容量の上限に達することができない場合があります。容量制限には、で到達できます https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["使用頻度の低いデータをオブジェクトストレージに階層化します"^]。
+
link:reference-limits-gcp.html["Google Cloud のディスク制限について詳しくは、こちらをご覧ください"]。

. ^2^Google Cloud Storageへのデータ階層化はPAYGO Exploreではサポートされていません。
. ^3^ Google Cloud にCloud Volumes ONTAPの新しいインスタンスをデプロイするときに、n1 シリーズのマシンはコンソールで選択できなくなりました。n1 シリーズのマシンは、古い既存のシステムでのみ保持され、サポートされます。Cloud Volumes ONTAPの新しいデプロイメントは、Google Cloud 9.8 リリース以降でのみサポートされます。Cloud Volumes ONTAP 9.8 以降と互換性のある n2 シリーズ マシンに切り替えることをお勧めします。ただし、n1 シリーズのマシンは、API を通じて実行される新しいデプロイメントに使用できます。
+
新しい Cloud Volumes ONTAP システムでは、 custom-4-16384 マシンタイプはサポートされなくなりました。このタイプのマシンで既存のシステムを実行している場合は、引き続き使用できますが、 n2 標準 -4 マシンタイプに切り替えることをお勧めします。

. ^4^Balanced Persistent DiskおよびPerformance（SSD）Persistent Diskを使用すると、書き込みパフォーマンスの向上が有効になります。


コンソールには、Standard および BYOL でサポートされている追加のマシン タイプ n1-highmem-4 が表示されます。ただし、このマシンタイプは実稼働環境向けではありません。特定のラボ環境でのみ利用できるようにしました。

Cloud Volumes ONTAP ソフトウェアバージョン9.13.0以降では、次のHAペア導入インスタンスで_Flash Cache_、高速の書き込み速度、最大伝送ユニット（MTU）8、896バイトを使用できます。

* N2-standard-16
* N2-standard-32
* N2-STANDARD-48
* N2-STANDARD-64


対象となるインスタンスタイプを導入する際に、_Flash Cache__、および高速の書き込み速度を有効にすることができます。より高い最大伝送単位（8、896バイト）をイネーブルにするには、導入環境でVPC-1、VPC-2、またはVPC-3を選択する必要があります。MTUが大きいほど、ネットワークスループットが向上します。これらの配置のいずれかを起動する方法の詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Google CloudでのHAペアの起動"]。


NOTE: _Flash Cache _、高書き込みモード、MTU 8、896は機能に依存し、設定されたインスタンス内で個別に無効にすることはできません。

--
====
特定のマシンタイプの詳細については、Google Cloud のドキュメントを参照してください。

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["n1シリーズ汎用機"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["N2シリーズ汎用機"^]




== サポートされるディスクサイズ

Google Cloud では、アグリゲートに同じタイプとサイズのディスクを 6 本まで含めることができます。次のディスクサイズがサポートされています。

* 100 GB
* 500 GB
* 1 TB
* 2TB
* 4 TB
* 8 TB
* 16 TB
* 64 TB




== サポートされている地域

Google Cloudリージョンのサポートについては、を参照してください https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volume グローバルリージョン"^]。
