---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.13.0には、新しい機能拡張が含まれています。 
---
= Cloud Volumes ONTAP 9.13.0の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.13.0には、新しい機能拡張が含まれています。

その他の機能や拡張機能も、最新バージョンのBlueXP（旧Cloud Manager）で導入されました。を参照してください https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["BlueXPリリースノート"^] を参照してください。



== 9.13.0 GA（2023年3月5日）

Cloud Volumes ONTAP 9.13.0の一般提供（GA）リリースが、AWS、Azure、Google Cloudで利用できるようになりました。このリリースには、次の新機能と機能拡張が含まれています。



=== Google CloudでのFlash Cacheと高速書き込み

Cloud Volumes ONTAP 9.13.0リリースでは、Flash Cache、高速な書き込み速度、最大転送単位（MTU）8、896バイトがサポートされるようになりました。

の詳細を確認してください link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Google Cloudのライセンスごとにサポートされる構成"^]。



=== Google Cloudでの画像検証

Google Cloudを介してエクスポートされたCloud Volumes ONTAP 画像ファイルの署名を検証するための強化されたセキュリティ機能が利用可能になりました。

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-gcp-image-verification.html["Google Cloudイメージ検証の詳細については、こちらをご覧ください"^]。



=== Google Cloudで新しいインスタンスがサポートされます

Freemium、PAYGO Premium、ノードベースのBYOL、容量ベースのライセンスで、Cloud Volumes ONTAP シングルノード環境とGoogle Cloudの高可用性環境の2つの新しいインスタンスタイプがサポートされるようになりました。

* N2-STANDARD-48
* N2-STANDARD-64


link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Google Cloudでサポートされる構成の詳細については、こちらをご覧ください"^]。



== アップグレードに関する注意事項

このリリースへのアップグレードの詳細については、以下のメモをお読みください。



=== アップグレード方法

Cloud Volumes ONTAP のアップグレードは、BlueXPから完了している必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響を与える可能性

link:http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXPから通知があった場合のアップグレード方法について説明します"^]。



=== サポートされているアップグレードパス

Cloud Volumes ONTAP 9.12.1リリースから9.13.0にアップグレードできます。BlueXPでは、対象となるCloud Volumes ONTAP システムをこのリリースにアップグレードするように求められます。



=== 必要なコネクタのバージョン

新しいCloud Volumes ONTAP 9.13.0システムを導入し、既存のシステムを9.13.0にアップグレードするには、BlueXP Connectorのバージョン3.9.26以降が実行されている必要があります。


TIP: コネクタの自動アップグレードはデフォルトで有効になっているため、最新バージョンを実行する必要があります。



=== ダウンタイム

* シングルノードシステムのアップグレードでは、 I/O が中断されるまで最大 25 分間システムがオフラインになります。
* HA ペアのアップグレードは無停止で、 I/O が中断されません。無停止アップグレードでは、各ノードが連携してアップグレードされ、クライアントへの I/O の提供が継続されます。




=== C4、M4、およびR4のインスタンスはサポートされなくなりました

AWSでは、C4、M4、およびR4 EC2インスタンスタイプはCloud Volumes ONTAP でサポートされなくなりました。C4、M4、またはR4インスタンスタイプで実行されている既存のシステムがある場合は、C5、m5、またはr5インスタンスファミリーでインスタンスタイプに変更する必要があります。インスタンスタイプを変更するまで、このリリースにアップグレードすることはできません。

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["Cloud Volumes ONTAP のEC2インスタンスタイプを変更する方法について説明します"^]。

を参照してください link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["ネットアップサポート"^] これらのインスタンスタイプの可用性とサポート終了の詳細については、を参照してください。
