---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.16.1には、新しい機能拡張が含まれています。 
---
= Cloud Volumes ONTAP 9.16.1の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.16.1には、新しい機能拡張が含まれています。

その他の機能と拡張機能も、最新バージョンのBlueXPで導入されました。を参照してください https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXPリリースノート"^] を参照してください。



== 9.16.1 P4（2025年7月8日）

AzureとGoogle Cloudで、9.16.1 P4パッチをCloud Volumes ONTAP向けに導入してアップグレードできるようになりました。ただし、このバージョンはAWSでの導入およびアップグレードには使用できません。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P4["P4パッチで修正されたバグの一覧を表示する"^] （NetAppサポートサイトへのログインが必要です）。



== 9.16.1 P3（2025年5月29日）

AzureとGoogle Cloudで、9.16.1 P3パッチをCloud Volumes ONTAP向けに導入してアップグレードできるようになりました。ただし、このバージョンはAWSでの導入およびアップグレードには使用できません。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P3["P3パッチで修正されたバグの一覧を表示する"^] （NetAppサポートサイトへのログインが必要です）。



== 9.16.1 P2（2025年4月17日）

AzureとGoogle Cloudで、9.16.1 P2パッチをCloud Volumes ONTAP向けに導入してアップグレードできるようになりました。ただし、このバージョンはAWSでの導入およびアップグレードには使用できません。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P2["P2パッチで修正されたバグの一覧を表示する"^] （NetAppサポートサイトへのログインが必要です）。



== 9.16.1 P1（2025年4月17日）

AzureとGoogle Cloudで、9.16.1 P1パッチをCloud Volumes ONTAP向けに導入してアップグレードできるようになりました。ただし、このバージョンはAWSでの導入およびアップグレードには使用できません。BlueXPでは、既存のシステムをこのパッチリリースにアップグレードするように求められます。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.16.1P1["P1パッチで修正されたバグの一覧を表示する"^] （NetAppサポートサイトへのログインが必要です）。



== 9.16.1 GA（2025年3月6日）

Cloud Volumes ONTAP 9.16.1 General Availabilityリリースを使用して、AzureとGoogle Cloudでの導入とアップグレードが可能になりました。ただし、このバージョンはAWSでの導入およびアップグレードには使用できません。



== アップグレードに関する注意事項

このリリースへのアップグレードの詳細については、以下のメモをお読みください。



=== アップグレード方法

Cloud Volumes ONTAP のアップグレードは、BlueXPから完了している必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響を与える可能性

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXPから通知があった場合のアップグレード方法について説明します"^]。



=== サポートされているアップグレードパス

AzureおよびGoogle Cloudでは、9.15.1リリースからCloud Volumes ONTAP 9.16.1 GAにアップグレードできます。BlueXPでは、対象となるCloud Volumes ONTAP システムをこのリリースにアップグレードするように求められます。


NOTE: AWSの場合、このアップグレードのプロンプトは表示されません。Cloud Volumes ONTAP 9.16.1 GAへのアップグレードは、AWSではサポートされていません。



=== ダウンタイム

* シングルノードシステムのアップグレードでは、 I/O が中断されるまで最大 25 分間システムがオフラインになります。
* HAペアのアップグレードは無停止で実行され、I/Oが中断されることはありません。この無停止アップグレードプロセスでは、クライアントへのI/O処理を継続するために、各ノードが同時にアップグレードされます。

