---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.19.1 には新しい機能強化が含まれています。 
---
= Cloud Volumes ONTAP 9.19.1 の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.19.1への導入とアップグレードが可能になりました。このリリースの基本バージョンと、展開およびアップグレードに使用できる最新のパッチ バージョンをNetApp Consoleで確認できます。

Cloud Volumes ONTAP の最新バージョンで導入された機能について知るには、NetApp Console の新機能をご覧ください https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^]。



[[9-19-1-rc-13-july-2026]]
== 9.19.1 RC（2026年7月13日）

Cloud Volumes ONTAP 9.19.1 リリース候補版 (RC) が、Google Cloud でのみデプロイおよびアップグレード可能になりました。このバージョンは、Amazon Web Services (AWS) および Microsoft Azure (Azure) へのデプロイおよびアップグレードには対応していません。



[[upgrade-notes]]
== アップグレードに関する注意事項

このリリースへのアップグレードの詳細については、以下のメモをお読みください。



[[how-to-upgrade]]
=== アップグレード方法

Cloud Volumes ONTAPのアップグレードはコンソールから完了する必要があります。System Manager または CLI を使用してCloud Volumes ONTAP をアップグレードしないでください。システムの安定性に影響を与える可能性があります。

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["コンソールから通知があった場合にアップグレードする方法を学びます"^] 。



[[supported-upgrade-path]]
=== サポートされているアップグレードパス

Google Cloud のみで、Cloud Volumes ONTAP 9.18.1 から 9.19.1 RC にアップグレードできます。コンソールは、このリリースへのアップグレード対象となる Cloud Volumes ONTAP システムへのアップグレードを促します。


NOTE: AWS と Azure では、これらのクラウドプロバイダーではこのバージョンのデプロイおよびアップグレードが利用できないため、9.19.1 RC へのアップグレードを促すメッセージは表示されません。



[[downtime]]
=== ダウンタイム

* 単一ノード システムをアップグレードすると、システムが最大 25 分間オフラインになり、その間 I/O が中断されます。
* HAペアのアップグレードは無停止で実行され、I/Oが中断されることはありません。この無停止アップグレードプロセスでは、クライアントへのI/O処理を継続するために、各ノードが同時にアップグレードされます。

