---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.17.1 には新しい機能強化が含まれています。 
---
= Cloud Volumes ONTAP 9.17.1 の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.17.1 は、Azure および Google Cloud で展開およびアップグレードできます。

NetApp Consoleの最新バージョンでは、追加の機能と拡張機能も導入されています。詳細については、 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^] コンソールで管理されます。



== 9.17.1 P1（2025年11月4日）

Cloud Volumes ONTAP 9.17.1 P1 パッチが、Azure および Google Cloud で展開およびアップグレードできるようになりました。ただし、このバージョンはAWSではデプロイおよびアップグレードできません。BlueXPコンソールは、既存のシステムをこのパッチ リリースにアップグレードするように要求します。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P1["P1パッチで修正されたバグのリストを見る"^](NetAppサポート サイトへのログインが必要です)。



== 9.17.1 RC1（2025年9月4日）

Cloud Volumes ONTAP 9.17.1 のリリース候補 1 を使用して、Azure および Google Cloud でデプロイおよびアップグレードできるようになりました。ただし、このバージョンはAWSではデプロイおよびアップグレードできません。BlueXP



== アップグレードに関する注意事項

このリリースへのアップグレードの詳細については、以下のメモをお読みください。



=== アップグレード方法

Cloud Volumes ONTAPのアップグレードは、 NetAppコンソールから完了する必要があります。System Manager または CLI を使用してCloud Volumes ONTAP をアップグレードしないでください。システムの安定性に影響を与える可能性があります。

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["コンソールから通知があった場合にアップグレードする方法を学びます"^] 。



=== サポートされているアップグレードパス

Azure および Google Cloud の 9.16.1 リリースからCloud Volumes ONTAP 9.17.1 RC1 にアップグレードできます。コンソールでは、対象となるCloud Volumes ONTAPシステムをこのリリースにアップグレードするように求められます。


NOTE: AWS の場合、このアップグレードを求めるプロンプトは表示されません。  Cloud Volumes ONTAP 9.17.1 RC1 へのアップグレードは AWS ではサポートされていません。



=== ダウンタイム

* シングルノードシステムのアップグレードでは、 I/O が中断されるまで最大 25 分間システムがオフラインになります。
* HAペアのアップグレードは無停止で実行され、I/Oが中断されることはありません。この無停止アップグレードプロセスでは、クライアントへのI/O処理を継続するために、各ノードが同時にアップグレードされます。

