---
sidebar: sidebar 
permalink: reference-provider-integrations.html 
keywords: maintenance event, azure maintenance event, cloud provider, issues, support, SMB CA in CVO 
summary: このページでは、ネットアップとクラウドプロバイダが連携して発生する可能性のある問題を解決する方法について説明します。 
---
= Cloud Volumes ONTAP向けクラウドプロバイダとのコラボレーション
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetAppがクラウドプロバイダと連携して潜在的な問題に対処する方法をご紹介します。



== 共同サポートのベストプラクティス

ネットアップは、ライセンシーにサポートを提供することを約束し、ライセンシーから報告された場合、 Cloud Volumes ONTAP のテクニカル・サポート問題を解決するために商業的に合理的な努力を払うものとします。ネットアップと該当するクラウドプロバイダは、相互にライセンスを供与されたソフトウェアやインフラに対する直接的なサポート義務を負いません。

ネットアップでは、該当するクラウドプロバイダサービスが原因で発生する可能性のある技術的な問題について、該当するクラウドプロバイダとの連携を目的としたツールを実装しています。ただし、 シームレスなサポートフローを維持する最善の方法は、（ i ）ネットアップと該当するクラウドプロバイダの両方と現在のサポート契約を維持し、（ ii ）技術的な問題が発生した場合には該当するクラウドプロバイダとの共同エスカレーションミーティングを調整することです これらの技術的な問題の原因となっている製品またはサービス。



== Azure メンテナンスイベント

Microsoft では、 Cloud Volumes ONTAP VM に影響する可能性があるメンテナンスイベントのスケジュールを設定し、プログラムによって Azure Virtual Machine （ VM ； Azure 仮想マシン）インフラに対する通知を行います。これらのイベントは、メンテナンス時間の 15 分前に通知されます。

メンテナンスイベントの特別な処理は、Cloud Volumes ONTAP高可用性（HA）ペアでサポートされています。アプリケーションの健全性を維持するために、安定性を優先する予防的なテイクオーバーを実行します。15秒を超える接続の損失により、フェイルオーバー機能が無効になるためです。

メンテナンス時間がアナウンスされると、対象のノードのパートナーノードがテイクオーバーを実行します。メンテナンスが完了すると、ギブバックが開始されます。ギブバックが完了すると、 HA ペアは正常な状態に戻ります。この問題が発生しない場合は、ネットアップサポートにお問い合わせください。メンテナンスイベントの対象は、 HA ペアの VM の 1 つです。通常、どちらのノードも比較的短時間です。

Cloud Volumes ONTAPの非継続的可用性CIFS共有を使用するCIFS/SMBクライアントは、テイクオーバーの発生時と、セッションで使用されているアグリゲートがアグリゲートのホームノードにギブバックされる際に、セッションが失われます。これはCIFS/SMBプロトコル自体によって課せられる制限です。テイクオーバーとギブバックに起因する問題を回避するには、承認済みのサードパーティ製品をご使用ください。ご不明な点がございましたら、 NetAppサポートまでお問い合わせください。


NOTE: https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["継続的可用性を備えたSMB共有"^]非中断運用はCloud Volumes ONTAPではサポートされていません。
